## Part a) 

Let’s start with the given image. If the starting number is 1, then we would say S = 1. Assuming we are to dial a 4-digit number starting from 1, Ω(1) = 1 for any number since we can start from any number. Getting to 2nd digit, we could say from 1 we can either go to 4 or 2. Now let’s break the digits. If we can go to 2 possible positions from 1, the Ω(1,2) = 2
With 2 digits covered, we have 2 more left. Building on the same logic
Ω(2,2) = 3. Or Ω(4,2) = 3. Both paths lead show the same Omega value

If we go with 5 as the next digit, the options would be:
Ω(5,2) = 4. (possible next digit is 2, 4, 8 or 6)

This is the highest value we can get from the current arrangements of numbers. Beyond this point, any next digit we pick will have an Omega of 3 at-least. If we choose 8 as next hop from 5, we will get Ω(8,2) = 4. Adding all these up will give us the Omega value. 

Ω(1,4) = 2+3+4+4 = 13

Using the matrix which shows the possibility of a path between 2 numbers. 


In [22]:
import numpy as np
a = np.array([
    [0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
    [0, 0, 1, 0, 1, 0, 0, 0, 0, 0],
    [0, 1, 0, 1, 0, 1, 0, 0, 0, 0],
    [0, 0, 1, 0, 0, 0, 1, 0, 0, 0],
    [0, 1, 0, 0, 0, 1, 0, 1, 0, 0],
    [0, 0, 1, 0, 1, 0, 1, 0, 1, 0],
    [0, 0, 0, 1, 0, 1, 0, 0, 0, 1],
    [0, 0, 0, 0, 1, 0, 0, 0, 1, 0],
    [1, 0, 0, 0, 0, 1, 0, 1, 0, 1],
    [0, 0, 0, 0, 0, 0, 1, 0, 1, 0]
])

print(a.shape)

(10, 10)


In [17]:
n = np.array([
    [1],
    [1],
    [1], 
    [1], 
    [1], 
    [1], 
    [1], 
    [1], 
    [1], 
    [1]])#.reshape(1,10)
print(n.shape)

(10, 1)


In [22]:
#1 Ω(N) = A × Ω(1) which means for 2 digit numbers
m2 = np.dot(a,n)
print(m2)

[[1]
 [2]
 [3]
 [2]
 [3]
 [4]
 [3]
 [2]
 [4]
 [2]]


In [23]:
#Ω(N) = A × Ω(2)+ #1
m3=np.dot(a,m2)
print(m3)

[[ 4]
 [ 6]
 [ 8]
 [ 6]
 [ 8]
 [13]
 [ 8]
 [ 7]
 [ 9]
 [ 7]]


In [25]:
m4 = np.dot(a,m3)
print(m4)

[[ 9]
 [16]
 [25]
 [16]
 [26]
 [33]
 [26]
 [17]
 [31]
 [17]]


In [72]:
import numpy as np
def findOmegaPaths(s,n):
    """
    A function to find number of unique n-digit paths on the dial pad for a given number S
    """
    dial_routes = np.array([
    [0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
    [0, 0, 1, 0, 1, 0, 0, 0, 0, 0],
    [0, 1, 0, 1, 0, 1, 0, 0, 0, 0],
    [0, 0, 1, 0, 0, 0, 1, 0, 0, 0],
    [0, 1, 0, 0, 0, 1, 0, 1, 0, 0],
    [0, 0, 1, 0, 1, 0, 1, 0, 1, 0],
    [0, 0, 0, 1, 0, 1, 0, 0, 0, 1],
    [0, 0, 0, 0, 1, 0, 0, 0, 1, 0],
    [1, 0, 0, 0, 0, 1, 0, 1, 0, 1],
    [0, 0, 0, 0, 0, 0, 1, 0, 1, 0]])
    #Each point can is a digit in itself so if we have to dial 1 digit number, for all numbers 1 path exists
    initial_number=np.array([
    [1],
    [1],
    [1], 
    [1], 
    [1], 
    [1], 
    [1], 
    [1], 
    [1], 
    [1]])
    
    #implementing A**(n-1) 
    paths=np.dot(dial_routes,dial_routes)
    for i in range(n-2):
        print(i,"th iteration")
        paths=np.dot(paths,dial_routes)
    #Multiplying with Ω(1)
    routes=np.dot(paths,initial_number)
    res = routes.T[0].tolist()[s-1]
    return(res)

In [73]:
om = findOmegaPaths(5,10)
print (om)

0 th iteration
1 th iteration
2 th iteration
3 th iteration
4 th iteration
5 th iteration
6 th iteration
7 th iteration
61390


## Part c) 
Lets transpose A and try to compare the original and the transpose

In [42]:
def compareMatrices(A,B):
    """
    This function takes 2 matrices and compares them element wise to determine equality
    """
    ##If the shape of the matrices is different there is no need to compare
    #they are already unequal
    if (A.shape == Atrans.shape):
        print("Matrices have same shape")
        if(A.all()==B.all()):
            return True
        else:
            return False
    else:
        print("cant compare matrices")
        return False
    

In [44]:
A = np.matrix(a)
Atrans = A.T
are_matrices_same = compareMatrices(A, Atrans)
print("Comparing similarity of matrices shows ",are_matrices_same)

Matrices have same shape
Comparing similarity of matrices shows  True


### As to whether did I expect the matrix and its transpose to be equal, the answer is yes, the reason is, if there is a path from 0->8, then there is a path from 8->0 as well. This is a non-directional problem. Hence the matrix and its transpose would be identical
