Part a) 

Let’s start with the given image. If the starting number is 1, then we would say S = 1. Assuming we are to dial a 4-digit number starting from 1, Ω(1) = 1 for any number since we can start from any number. Getting to 2nd digit, we could say from 1 we can either go to 4 or 2. Now let’s break the digits. If we can go to 2 possible positions from 1, the Ω(1,2) = 2
With 2 digits covered, we have 8 more left. Building on the same logic
Ω(2,2) = 3. Or Ω(4,2) = 3. Both paths lead show the same Omega value

If we go with 5 as the next digit, the options would be:
Ω(5,2) = 4. (possible next digit is 2, 4, 8 or 6)

This is the highest value we can get from the current arrangements of numbers. Beyond this point, we any next digit we pick will have an Omega of 3 at-least. If we choose 8 as next hop from 5, we will get Ω(8,2) = 4. Adding all these up will give us the Omega value. 

Ω(1,4) = 2+3+4+4 = 13

Using the matrix which shows the possibility of a path between 2 numbers. 


In [15]:
import numpy as np
a = np.array([
    [0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
    [0, 0, 1, 0, 1, 0, 0, 0, 0, 0],
    [0, 1, 0, 1, 0, 1, 0, 0, 0, 0],
    [0, 0, 1, 0, 0, 0, 1, 0, 0, 0],
    [0, 1, 0, 0, 0, 1, 0, 1, 0, 0],
    [0, 0, 1, 0, 1, 0, 1, 0, 1, 0],
    [0, 0, 0, 1, 0, 1, 0, 0, 0, 1],
    [0, 0, 0, 0, 1, 0, 0, 0, 1, 0],
    [1, 0, 0, 0, 0, 1, 0, 1, 0, 1],
    [0, 0, 0, 0, 0, 0, 1, 0, 1, 0]
])

print(a.shape)

(10, 10)


In [17]:
n = np.array([
    [1],
    [1],
    [1], 
    [1], 
    [1], 
    [1], 
    [1], 
    [1], 
    [1], 
    [1]])#.reshape(1,10)
print(n.shape)

(10, 1)


In [22]:
#1 Ω(N) = A × Ω(1)
m2 = np.dot(a,n)
print(m2)

[[1]
 [2]
 [3]
 [2]
 [3]
 [4]
 [3]
 [2]
 [4]
 [2]]


In [23]:
#Ω(N) = A × Ω(2)+ #1
m3=np.dot(a,m2)
print(m3)

[[ 4]
 [ 6]
 [ 8]
 [ 6]
 [ 8]
 [13]
 [ 8]
 [ 7]
 [ 9]
 [ 7]]


In [25]:
m4 = np.dot(a,m3)
print(m4)

[[ 9]
 [16]
 [25]
 [16]
 [26]
 [33]
 [26]
 [17]
 [31]
 [17]]
